// AUTO-GENERATED by scripts/generate.mjs - DO NOT EDIT
// Run `npm run build` to regenerate

/**
 * Tool names as a const tuple for use with z.enum().
 * Generated from ALL_TOOLS at build time.
 */
export const TOOL_NAMES = [
  'grist_discover_tools',
  'grist_get_workspaces',
  'grist_get_documents',
  'grist_get_tables',
  'grist_query_sql',
  'grist_get_records',
  'grist_manage_records',
  'grist_manage_schema',
  'grist_manage_pages',
  'grist_create_document',
  'grist_manage_webhooks',
  'grist_help'
] as const

export type ToolName = (typeof TOOL_NAMES)[number]
