// Generated by dts-bundle-generator v9.5.1
// Grist Core Type Definitions
// Source: Provided by user for reference

declare enum GristObjCode {
  List = "L",
  LookUp = "l",
  Dict = "O",
  DateTime = "D",
  Date = "d",
  Skip = "S",
  Censored = "C",
  Reference = "R",
  ReferenceList = "r",
  Exception = "E",
  Pending = "P",
  Unmarshallable = "U",
  Versions = "V",
}
/**
 * Possible types of cell content.
 *
 * Each `CellValue` may either be a primitive (e.g. `true`, `123`, `"hello"`, `null`)
 * or a tuple (JavaScript Array) representing a Grist object. The first element of the tuple
 * is a string character representing the object code. For example, `["L", "foo", "bar"]`
 * is a `CellValue` of a Choice List column, where `"L"` is the type, and `"foo"` and
 * `"bar"` are the choices.
 *
 * ### Grist Object Types
 *
 * | Code | Type           |
 * | ---- | -------------- |
 * | `L`  | List, e.g. `["L", "foo", "bar"]` or `["L", 1, 2]` |
 * | `l`  | LookUp, as `["l", value, options]` |
 * | `O`  | Dict, as `["O", {key: value, ...}]` |
 * | `D`  | DateTimes, as `["D", timestamp, timezone]`, e.g. `["D", 1704945919, "UTC"]` |
 * | `d`  | Date, as `["d", timestamp]`, e.g. `["d", 1704844800]` |
 * | `C`  | Censored, as `["C"]` |
 * | `R`  | Reference, as `["R", table_id, row_id]`, e.g. `["R", "People", 17]` |
 * | `r`  | ReferenceList, as `["r", table_id, row_id_list]`, e.g. `["r", "People", [1,2]]` |
 * | `E`  | Exception, as `["E", name, ...]`, e.g. `["E", "ValueError"]` |
 * | `P`  | Pending, as `["P"]` |
 * | `U`  | Unmarshallable, as `["U", text_representation]` |
 * | `V`  | Version, as `["V", version_obj]` |
 */
export type CellValue =
  | number
  | string
  | boolean
  | null
  | [GristObjCode, ...unknown[]];
export interface BulkColValues {
  [colId: string]: CellValue[];
}
export type GristType =
  | "Any"
  | "Attachments"
  | "Blob"
  | "Bool"
  | "Choice"
  | "ChoiceList"
  | "Date"
  | "DateTime"
  | "Id"
  | "Int"
  | "ManualSortPos"
  | "Numeric"
  | "PositionNumber"
  | "Ref"
  | "RefList"
  | "Text"; // Note that "Ref" and "RefList" need to be used like Ref:EgTableID

declare enum RecalcWhen {
  DEFAULT = 0, // Calculate on new records or when any field in recalcDeps changes.
  NEVER = 1, // Don't calculate automatically (but user can trigger manually)
  MANUAL_UPDATES = 2,
}
export type AddRecord = ["AddRecord", string, number, ColValues];
export type BulkAddRecord = ["BulkAddRecord", string, number[], BulkColValues];
export type RemoveRecord = ["RemoveRecord", string, number];
export type BulkRemoveRecord = ["BulkRemoveRecord", string, number[]];
export type UpdateRecord = ["UpdateRecord", string, number, ColValues];
export type BulkUpdateRecord = [
  "BulkUpdateRecord",
  string,
  number[],
  BulkColValues
];
export type ReplaceTableData = [
  "ReplaceTableData",
  string,
  number[],
  BulkColValues
];
export type TableDataAction = ["TableData", string, number[], BulkColValues];
export type AddColumn = ["AddColumn", string, string, ColInfo];
export type RemoveColumn = ["RemoveColumn", string, string];
export type RenameColumn = ["RenameColumn", string, string, string];
export type ModifyColumn = ["ModifyColumn", string, string, Partial<ColInfo>];
export type AddTable = ["AddTable", string, ColInfoWithId[]];
export type RemoveTable = ["RemoveTable", string];
export type RenameTable = ["RenameTable", string, string];
export type DocAction =
  | AddRecord
  | BulkAddRecord
  | RemoveRecord
  | BulkRemoveRecord
  | UpdateRecord
  | BulkUpdateRecord
  | ReplaceTableData
  | TableDataAction
  | AddColumn
  | RemoveColumn
  | RenameColumn
  | ModifyColumn
  | AddTable
  | RemoveTable
  | RenameTable;
export interface ColValues {
  [colId: string]: CellValue;
}
export interface ColInfo {
  colId: string;
  type: string;
  label: string;
  isFormula: boolean;
  formula: string;
  description: string;
  recalcDeps: number[] | null;
  recalcWhen: RecalcWhen;
  visibleCol: number;
  untieColIdFromLabel: boolean;
  widgetOptions: string;
}
export interface ColInfoWithId extends ColInfo {
  id: string;
}
export interface Style {
  textColor?: string | undefined;
  fillColor?: string | undefined;
  fontBold?: boolean | undefined;
  fontUnderline?: boolean | undefined;
  fontItalic?: boolean | undefined;
  fontStrikethrough?: boolean | undefined;
}
export interface HeaderStyle {
  headerTextColor?: string | undefined;
  headerFillColor?: string | undefined;
  headerFontBold?: boolean | undefined;
  headerFontUnderline?: boolean | undefined;
  headerFontItalic?: boolean | undefined;
  headerFontStrikethrough?: boolean | undefined;
}
/**
 * Number format modes for numeric columns
 */
export type NumberFormat =
  | "currency"
  | "decimal"
  | "percent"
  | "scientific"
  | "text";
/**
 * Text alignment options
 */
export type TextAlignment = "left" | "center" | "right";
/**
 * Widget types for different column types
 */
export type WidgetType =
  | "TextBox"
  | "Markdown"
  | "HyperLink"
  | "Spinner"
  | "CheckBox"
  | "Switch";
/**
 * Choice style configuration for individual choices
 */
export interface ChoiceOptions {
  [choice: string]: Style;
}
/**
 * Complete widget options for column configuration
 */
export interface WidgetOptions extends Style, HeaderStyle {
  /** Widget type to use for display */
  widget?: WidgetType;
  /** Number display mode (currency, decimal, percent, scientific) */
  numMode?: NumberFormat | null;
  /** ISO 4217 currency code (e.g., "USD", "EUR", "GBP") */
  currency?: string;
  /** Number sign display (null for minus, "parens" for parentheses) */
  numSign?: "parens" | null;
  /** Minimum number of decimal places to display */
  decimals?: number;
  /** Maximum number of decimal places to display */
  maxDecimals?: number;
  /** Date format string */
  dateFormat?: string;
  /** Whether the date format is custom */
  isCustomDateFormat?: boolean;
  /** Time format string */
  timeFormat?: string;
  /** Whether the time format is custom */
  isCustomTimeFormat?: boolean;
  /** Attachment display height */
  height?: number;
  /** Text alignment */
  alignment?: TextAlignment;
  /** Enable text wrapping */
  wrap?: boolean;
  /** Available choices for Choice/ChoiceList columns */
  choices?: string[];
  /** Style configuration for individual choices */
  choiceOptions?: ChoiceOptions;
}

export {};
